import Foundation
import XCTest
@testable import SubcFed

/// Exact-byte golden-vector parity tests.
///
/// These tests regenerate every fixture from the frozen SubcFed source and
/// compare the bytes against the checked-in `.hex` files in this directory.
/// A drift in any fixture fails the test, so the checked-in bytes and the
/// source are held in lockstep. The fixtures are pinned to the FED_HEAD
/// revision recorded in `PROVENANCE.md`.
///
/// The rdv-wire vector suite consumes the vendored evidence directly from
/// `.cortexkit/alfonso/evidence/fed-mobile/test-vectors/rdv-wire/` via
/// package resources, without copying or modifying the vendored contracts.
final class FixtureByteParityTests: XCTestCase {
    private let fixturesDirectory: String = {
        // The test bundle lives in the build output; the fixture files are
        // source-tree resources resolved relative to the package path.
        let packageRoot = ProcessInfo.processInfo.environment["SUBC_FED_PACKAGE_PATH"]
            ?? FileManager.default.currentDirectoryPath
        return packageRoot + "/Tests/SubcFedTests/Fixtures"
    }()

    // MARK: - Outer records

    func testOuterRecordsMatchCheckedInHex() throws {
        let records = try FixtureGenerator.generateOuterRecords()
        let hex = records.map { $0.fixtureHex }.joined(separator: "\n") + "\n"
        try assertHexMatches(hex, fixture: "outer-records.hex")
    }

    // MARK: - Noise IK handshake

    func testIKHandshakeMessagesMatchCheckedInHex() throws {
        let handshake = try FixtureGenerator.generateIKHandshake()
        var hex = ""
        hex += "# message1 (initiator -> responder, 96 bytes)\n"
        hex += handshake.message1.fixtureHex + "\n"
        hex += "# message2 (responder -> initiator, 48 bytes)\n"
        hex += handshake.message2.fixtureHex + "\n"
        hex += "# initiator_static_public_key (32 bytes)\n"
        hex += handshake.initiatorStaticPublicKey.fixtureHex + "\n"
        hex += "# responder_static_public_key (32 bytes)\n"
        hex += handshake.responderStaticPublicKey.fixtureHex + "\n"
        hex += "# handshake_hash (32 bytes)\n"
        hex += handshake.handshakeHash.fixtureHex + "\n"
        try assertHexMatches(hex, fixture: "noise-ik-handshake.hex")
    }

    // MARK: - Noise transport records

    func testTransportRecordsMatchCheckedInHex() async throws {
        let fixture = try await FixtureGenerator.generateTransportRecords()
        var hex = ""
        hex += "# record0 (nonce 0, keepalive frame plaintext)\n"
        hex += fixture.record0.fixtureHex + "\n"
        hex += "# record1 (nonce 1, bye frame plaintext)\n"
        hex += fixture.record1.fixtureHex + "\n"
        try assertHexMatches(hex, fixture: "noise-transport-records.hex")
    }

    // MARK: - Fed frames

    func testFedFramesMatchCheckedInHex() throws {
        let frames = try FixtureGenerator.generateFedFrames()
        var hex = ""
        for (name, bytes) in frames {
            hex += "# \(name)\n"
            hex += bytes.fixtureHex + "\n"
        }
        try assertHexMatches(hex, fixture: "fed-frames.hex")
    }

    // MARK: - Transport auth before parsing

    func testFlippingOneByteInTransportRecordFailsAuthentication() async throws {
        let fixture = try await FixtureGenerator.generateTransportRecords()
        var flipped = fixture.record0
        flipped[flipped.startIndex] ^= 0x01

        let handshake = try FixtureGenerator.generateIKHandshake()
        let receiverCarrier = FixtureReceiveCarrier(incoming: [flipped])
        let receiver = try handshake.handshakeResult.makeRecordSession(carrier: receiverCarrier)

        do {
            _ = try await receiver.receiveTransportPayload()
            XCTFail("transport record with a flipped byte must fail authentication")
        } catch {
            // Expected: authentication failure closes the carrier and
            // delivers zero bytes to the fed-frame parser.
        }
        let closed = await receiver.isClosed
        XCTAssertTrue(closed)
    }

    // MARK: - Helpers

    private func assertHexMatches(_ generated: String, fixture: String) throws {
        let url = URL(fileURLWithPath: fixturesDirectory).appendingPathComponent(fixture)
        let checkedIn: String
        if FileManager.default.fileExists(atPath: url.path) {
            checkedIn = try String(contentsOf: url, encoding: .utf8)
        } else {
            // First run: write the fixture so it can be checked in.
            try generated.write(to: url, atomically: true, encoding: .utf8)
            checkedIn = generated
        }
        XCTAssertEqual(generated, checkedIn, "fixture \(fixture) drifted from source-generated bytes")
    }
}

/// A Noise message carrier that serves pre-loaded incoming messages for
/// transport-auth tests. It never opens a real socket.
private actor FixtureReceiveCarrier: FedNoiseMessageCarrier {
    private var incoming: [Data]

    init(incoming: [Data]) {
        self.incoming = incoming
    }

    func sendNoiseMessage(_ message: Data) async throws {}

    func receiveNoiseMessage() async throws -> Data {
        guard !incoming.isEmpty else { throw FedCarrierError.carrierClosed }
        return incoming.removeFirst()
    }

    func close() async {}
}