import Foundation
import CryptoKit

/// Abstraction over the local Noise static identity and optional relay companion
/// signing key. Production embeddings back this with the platform Keychain;
/// tests inject an in-memory store. Private key bytes must never appear in logs,
/// defaults, fixtures, or error text.
public protocol FedPrivateKeyStore: Sendable {
    /// 32-byte X25519 static public key for the local Noise identity.
    func staticPublicKey() async throws -> Data

    /// 32-byte X25519 static private key material.
    func staticPrivateKey() async throws -> Data

    /// Optional 32-byte Ed25519 companion private key used for relay proofs.
    /// Returns `nil` when the embedding has not enrolled a companion key.
    func companionSigningPrivateKey() async throws -> Data?
}

/// In-memory key store for deterministic tests. Production construction must
/// never silently substitute this for a Keychain-backed store.
public struct FedMemoryPrivateKeyStore: FedPrivateKeyStore, Sendable {
    private let noisePrivateKey: Data
    private let companionPrivateKey: Data?

    public init(noisePrivateKey: Data, companionSigningPrivateKey: Data? = nil) throws {
        guard noisePrivateKey.count == 32 else {
            throw FedFailure.invalidProfile(field: "noisePrivateKey")
        }
        if let companionSigningPrivateKey {
            guard companionSigningPrivateKey.count == 32 else {
                throw FedFailure.invalidProfile(field: "companionSigningPrivateKey")
            }
        }
        // Validate the private key is accepted by Curve25519 before storing it.
        _ = try Curve25519.KeyAgreement.PrivateKey(rawRepresentation: noisePrivateKey)
        if let companionSigningPrivateKey {
            _ = try Curve25519.Signing.PrivateKey(rawRepresentation: companionSigningPrivateKey)
        }
        self.noisePrivateKey = noisePrivateKey
        self.companionPrivateKey = companionSigningPrivateKey
    }

    public func staticPublicKey() async throws -> Data {
        let privateKey = try Curve25519.KeyAgreement.PrivateKey(rawRepresentation: noisePrivateKey)
        return privateKey.publicKey.rawRepresentation
    }

    public func staticPrivateKey() async throws -> Data {
        noisePrivateKey
    }

    public func companionSigningPrivateKey() async throws -> Data? {
        companionPrivateKey
    }
}

/// Raw keychain item operations behind FedKeychainPrivateKeyStore. Production
/// backs this with the Security framework; tests inject a controllable backing to
/// drive the first-load add race deterministically. readItem returns nil when no
/// item exists; addItemIfAbsent returns false when an item already exists (the
/// SecItemAdd errSecDuplicateItem outcome) so the caller can re-read the persisted
/// winner instead of trusting its own generated bytes.
protocol FedKeychainBacking: Sendable {
    func readItem(service: String, account: String) async throws -> Data?
    func addItemIfAbsent(_ data: Data, service: String, account: String) async throws -> Bool
}

/// Security-framework backing. Queries opt into the data-protection keychain so
/// items live in the keychain the iOS app seat configures via entitlements.
struct SecurityFrameworkKeychainBacking: FedKeychainBacking {
    func readItem(service: String, account: String) async throws -> Data? {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: account,
            kSecReturnData as String: true,
            kSecMatchLimit as String: kSecMatchLimitOne,
            kSecUseDataProtectionKeychain as String: true,
        ]
        var item: CFTypeRef?
        let status = SecItemCopyMatching(query as CFDictionary, &item)
        if status == errSecItemNotFound {
            return nil
        }
        guard status == errSecSuccess, let data = item as? Data else {
            throw FedFailure.storeUnavailable
        }
        return data
    }

    func addItemIfAbsent(_ data: Data, service: String, account: String) async throws -> Bool {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: account,
            kSecValueData as String: data,
            kSecAttrAccessible as String: kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly,
            kSecUseDataProtectionKeychain as String: true,
        ]
        let status = SecItemAdd(query as CFDictionary, nil)
        // A duplicate means another writer won the first-load race; report it so
        // the caller re-reads the persisted winner rather than diverging.
        if status == errSecDuplicateItem {
            return false
        }
        guard status == errSecSuccess else {
            throw FedFailure.storeUnavailable
        }
        return true
    }
}

/// Keychain-backed production store. Keys are never written to package files,
/// logs, or errors.
///
/// iOS embedding note: queries opt into the data-protection keychain via
/// kSecUseDataProtectionKeychain. The iOS application embedding this library must
/// supply a shared kSecAttrAccessGroup when the daemon and app extensions share
/// one identity, and choose a kSecAttrAccessible level that supports its
/// before-first-unlock requirement. AfterFirstUnlockThisDeviceOnly is unavailable
/// while the device is locked before its first unlock, so a client that must dial
/// from that state needs an accessibility level the embedding explicitly approves.
/// The create-on-first-load logic below is correct independent of both choices.
public struct FedKeychainPrivateKeyStore: FedPrivateKeyStore, Sendable {
    public let service: String
    public let noiseAccount: String
    public let companionAccount: String?
    private let backing: any FedKeychainBacking

    public init(
        service: String = "io.cortexkit.subc.fed",
        noiseAccount: String = "noise-static-x25519",
        companionAccount: String? = "relay-companion-ed25519"
    ) {
        self.service = service
        self.noiseAccount = noiseAccount
        self.companionAccount = companionAccount
        self.backing = SecurityFrameworkKeychainBacking()
    }

    /// Test seam: inject a controllable backing to exercise the first-load race.
    init(
        service: String = "io.cortexkit.subc.fed",
        noiseAccount: String = "noise-static-x25519",
        companionAccount: String? = "relay-companion-ed25519",
        backing: any FedKeychainBacking
    ) {
        self.service = service
        self.noiseAccount = noiseAccount
        self.companionAccount = companionAccount
        self.backing = backing
    }

    public func staticPublicKey() async throws -> Data {
        let privateKey = try await loadNoisePrivateKey()
        return privateKey.publicKey.rawRepresentation
    }

    public func staticPrivateKey() async throws -> Data {
        try await loadNoisePrivateKey().rawRepresentation
    }

    public func companionSigningPrivateKey() async throws -> Data? {
        guard let companionAccount else { return nil }
        return try await backing.readItem(service: service, account: companionAccount)
    }

    private func loadNoisePrivateKey() async throws -> Curve25519.KeyAgreement.PrivateKey {
        if let existing = try await backing.readItem(service: service, account: noiseAccount) {
            return try Curve25519.KeyAgreement.PrivateKey(rawRepresentation: existing)
        }
        // First load. Creation must be linearizable: two concurrent first-loaders
        // (two awaits in one dial cycle, or two processes) can both observe
        // absence and both generate DIFFERENT candidate keys, but only one
        // SecItemAdd wins. The persisted key is authoritative. Generate, add, and
        // on duplicate RE-READ the persisted winner and return THAT, so the
        // returned key always equals the durable key and the static Noise
        // identity never flaps across launches (which would silently break peer
        // pubkey-pinning and the pubkey-ordered dial tiebreak).
        let generated = Curve25519.KeyAgreement.PrivateKey()
        let added = try await backing.addItemIfAbsent(
            generated.rawRepresentation,
            service: service,
            account: noiseAccount
        )
        if added {
            return generated
        }
        // Lost the add race: the winner's key is the persisted one. Re-read and
        // return it rather than diverging with our un-persisted generated key.
        guard let winner = try await backing.readItem(service: service, account: noiseAccount) else {
            // A duplicate was reported yet no item is readable. Fail closed
            // instead of returning a key that is not the persisted identity.
            throw FedFailure.storeUnavailable
        }
        return try Curve25519.KeyAgreement.PrivateKey(rawRepresentation: winner)
    }
}
